#!/bin/sh
#
# This is a sample script for burning a VCD
# You have to adapt the DEVICE and DRIVER variables
# to the values of your CD burner
#

DEVICE="5,0"  # SCSI id and lun
DRIVER="generic-mmc"

# Remove the following 2 lines
echo "This is a sample script, edit it first"
exit

cdrdao write --device $DEVICE --driver $DRIVER vcd.toc
